### ISSUE TITLE
Trigger new autossh after closing CLOSE_WAIT

### ISSUE THREAD

**Issue by ShaneDeconinck** [kubo-global/Kubo-Global-Management-Console#15]
Problem:
I started with
<img width="705" alt="schermafbeelding 2018-11-07 om 16 47 58" src="https://user-images.githubusercontent.com/7532341/48142607-5e0e1180-e2ad-11e8-9f80-db018773a640.png">

Too many with state CLOSE_WAIT.

So I installed: 
`$ apt-get install libnet-rawip-perl libnet-pcap-perl libnetpacket-perl`

```
$ mv kill_close_wait_connections.pl /usr/bin/kill_close_wait_connections
$ chmod +x /usr/bin/kill_close_wait_connections
$ kill_close_wait_connections
```

(source: https://github.com/rghose/kill-close-wait-connections)

Then I got this:
<img width="693" alt="schermafbeelding 2018-11-07 om 16 50 10" src="https://user-images.githubusercontent.com/7532341/48142608-5e0e1180-e2ad-11e8-94ae-b108625a4c0a.png">

But lost connection with the KUBO server. So we should be able to catch this.

**Comment by Rgoetinck** [comment]
The reverse tunnel is now closing hung connections before re-establishing new ones, I would consider ticket closed :+1:

**Comment by ShaneDeconinck** [comment]
Awesome!
